// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.Persistencia.Models;

public partial class Asignatura
{
    public int IdAsignatura { get; set; }

    public string CodigoAsignatura { get; set; }

    public string NombreAsignatura { get; set; }

    public int? Semestre { get; set; }

    public virtual ICollection<AsistenciaEstudiante> AsistenciaEstudiantes { get; set; } = new List<AsistenciaEstudiante>();

    public virtual ICollection<DetalleMatricula> DetalleMatriculas { get; set; } = new List<DetalleMatricula>();

    public virtual ICollection<DocenteAsignatura> DocenteAsignaturas { get; set; } = new List<DocenteAsignatura>();
}