// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.Persistencia.Models;

public partial class AsistenciaEstudiante
{
    public int IdAsistencia { get; set; }

    public int IdEstudiante { get; set; }

    public int IdAsignatura { get; set; }

    public int IdDocente { get; set; }

    public DateOnly FechaAsistencia { get; set; }

    public TimeOnly HoraRegistro { get; set; }

    public string EstadoAsistencia { get; set; }

    public virtual Asignatura IdAsignaturaNavigation { get; set; }

    public virtual Docente IdDocenteNavigation { get; set; }

    public virtual Estudiante IdEstudianteNavigation { get; set; }
}