// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.Persistencia.Models;

public partial class Docente
{
    public int IdDocente { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Cedula { get; set; }

    public string Celular { get; set; }

    public string Correo { get; set; }

    public int IdCarrera { get; set; }

    public int IdAsignatura { get; set; }

    public DateOnly? FechaAsistencia { get; set; }

    public TimeOnly? HoraEntrada { get; set; }

    public TimeOnly? HoraSalida { get; set; }

    public string EstadoAsistencia { get; set; }

    public virtual Asignatura IdAsignaturaNavigation { get; set; }

    public virtual Carrera IdCarreraNavigation { get; set; }
}