// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.DemoConsola.Models;

public partial class Asignatura
{
    public int IdAsignatura { get; set; }

    public string CodigoAsignatura { get; set; }

    public string NombreAsignatura { get; set; }

    public int? Semestre { get; set; }

    public virtual ICollection<Docente> Docentes { get; set; } = new List<Docente>();
}