// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Proyecto.AsistenciaUNACH.DemoConsola.Models;

public partial class AsistenciaUNACHContext : DbContext
{
    public AsistenciaUNACHContext(DbContextOptions<AsistenciaUNACHContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Asignatura> Asignaturas { get; set; }

    public virtual DbSet<Carrera> Carreras { get; set; }

    public virtual DbSet<Docente> Docentes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Asignatura>(entity =>
        {
            entity.HasKey(e => e.IdAsignatura).HasName("PK__Asignatu__DD251214DEBF2A25");

            entity.ToTable("Asignatura");

            entity.HasIndex(e => e.CodigoAsignatura, "UQ__Asignatu__015B1399CB799023").IsUnique();

            entity.Property(e => e.IdAsignatura).HasColumnName("idAsignatura");
            entity.Property(e => e.CodigoAsignatura)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codigoAsignatura");
            entity.Property(e => e.NombreAsignatura)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombreAsignatura");
            entity.Property(e => e.Semestre).HasColumnName("semestre");
        });

        modelBuilder.Entity<Carrera>(entity =>
        {
            entity.HasKey(e => e.IdCarrera).HasName("PK__Carrera__7B19E791B3049903");

            entity.ToTable("Carrera");

            entity.HasIndex(e => e.CodigoCarrera, "UQ__Carrera__68B0C8911A5589D9").IsUnique();

            entity.Property(e => e.IdCarrera).HasColumnName("idCarrera");
            entity.Property(e => e.CodigoCarrera)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codigoCarrera");
            entity.Property(e => e.Facultad)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("facultad");
            entity.Property(e => e.Modalidad)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("modalidad");
            entity.Property(e => e.NombreCarrera)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombreCarrera");
        });

        modelBuilder.Entity<Docente>(entity =>
        {
            entity.HasKey(e => e.IdDocente).HasName("PK__Docente__595F5B9C9EB76891");

            entity.ToTable("Docente");

            entity.HasIndex(e => e.Correo, "UQ__Docente__2A586E0B50B64C1C").IsUnique();

            entity.HasIndex(e => e.Cedula, "UQ__Docente__415B7BE51FC8D655").IsUnique();

            entity.Property(e => e.IdDocente).HasColumnName("idDocente");
            entity.Property(e => e.Apellidos)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellidos");
            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("cedula");
            entity.Property(e => e.Celular)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("celular");
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.EstadoAsistencia)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estadoAsistencia");
            entity.Property(e => e.FechaAsistencia).HasColumnName("fechaAsistencia");
            entity.Property(e => e.HoraEntrada).HasColumnName("horaEntrada");
            entity.Property(e => e.HoraSalida).HasColumnName("horaSalida");
            entity.Property(e => e.IdAsignatura).HasColumnName("idAsignatura");
            entity.Property(e => e.IdCarrera).HasColumnName("idCarrera");
            entity.Property(e => e.Nombres)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombres");

            entity.HasOne(d => d.IdAsignaturaNavigation).WithMany(p => p.Docentes)
                .HasForeignKey(d => d.IdAsignatura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Docente_Asignatura");

            entity.HasOne(d => d.IdCarreraNavigation).WithMany(p => p.Docentes)
                .HasForeignKey(d => d.IdCarrera)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Docente_Carrera");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}