// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.DemoConsola.Models;

public partial class Carrera
{
    public int IdCarrera { get; set; }

    public string CodigoCarrera { get; set; }

    public string NombreCarrera { get; set; }

    public string Facultad { get; set; }

    public string Modalidad { get; set; }

    public virtual ICollection<Docente> Docentes { get; set; } = new List<Docente>();

    public virtual ICollection<Estudiante> Estudiantes { get; set; } = new List<Estudiante>();
}