// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.DemoConsola.Models;

public partial class DetalleMatricula
{
    public int IdMatricula { get; set; }

    public int IdEstudiante { get; set; }

    public int IdAsignatura { get; set; }

    public virtual Asignatura IdAsignaturaNavigation { get; set; }

    public virtual Estudiante IdEstudianteNavigation { get; set; }
}