// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.AsistenciaUNACH.DemoConsola.Models;

public partial class Estudiante
{
    public int IdEstudiante { get; set; }

    public string CodigoEstudiante { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public int Semestre { get; set; }

    public string Estado { get; set; }

    public int IdCarrera { get; set; }

    public virtual ICollection<AsistenciaEstudiante> AsistenciaEstudiantes { get; set; } = new List<AsistenciaEstudiante>();

    public virtual ICollection<DetalleMatricula> DetalleMatriculas { get; set; } = new List<DetalleMatricula>();

    public virtual Carrera IdCarreraNavigation { get; set; }
}